// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xicsrtoywqudvelgwyjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpY3NydG95d3F1ZHZlbGd3eWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NDEyMjgsImV4cCI6MjA3NzIxNzIyOH0.vTD2TkIBfuwA6VVdNNB5kaU446kaIf2O46k1P3o-KTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});